/**
 * Report Generator
 * Generates human-readable reports from recorded sessions
 */

import * as fs from "fs/promises";
import * as path from "path";
import { RunManifest, RunSummary } from "../types/index.js";

export class ReportGenerator {
  constructor(private manifest: RunManifest) {}

  generateMarkdown(): string {
    const lines: string[] = [];

    // Header
    lines.push("# Trailhound Report\n");
    lines.push(`**Run:** ${this.manifest.run.id}`);
    lines.push(`**Agent:** ${this.manifest.agent.name}`);
    lines.push(`**Started:** ${new Date(this.manifest.run.timestamp).toLocaleString()}`);
    lines.push(`**Duration:** ${this.formatDuration(this.manifest.run.durationMs)}`);
    lines.push(`**Exit Code:** ${this.manifest.run.exitCode}`);
    lines.push("");

    // Risk badge
    const riskLevel = this.calculateRiskLevel();
    lines.push(`## Risk Score: ${riskLevel.level}`);
    if (riskLevel.points > 0) {
      lines.push(`**${riskLevel.points} points** - ${riskLevel.reasons.join(", ")}`);
    }
    lines.push("");

    // Summary
    lines.push("## Summary");
    lines.push(`- **Files Modified:** ${this.manifest.summary.filesModified}`);
    lines.push(`- **Commands Run:** ${this.manifest.summary.commandsRun}`);
    lines.push(`- **Network Connections:** ${this.manifest.summary.networkConnections}`);
    lines.push(`- **Secrets Accessed:** ${this.manifest.summary.secretsAccessed}`);
    lines.push("");

    // Warnings
    if (this.manifest.warnings.length > 0) {
      lines.push("## Warnings");
      this.manifest.warnings.forEach(w => {
        lines.push(`- ⚠️  ${w}`);
      });
      lines.push("");
    }

    // Repository info
    if (this.manifest.repo.git.isRepo) {
      lines.push("## Repository");
      lines.push(`- **Branch:** ${this.manifest.repo.git.branch || "unknown"}`);
      lines.push(`- **Commit:** ${this.manifest.repo.git.commit?.slice(0, 8) || "unknown"}`);
      if (this.manifest.repo.git.dirty) {
        lines.push("- **Status:** ⚠️  Uncommitted changes");
      }
      lines.push("");
    }

    // Footer
    lines.push("---");
    lines.push(`*Generated by Trailhound v0.1.0*\n`);

    return lines.join("\n");
  }

  async generateMarkdownReport(): Promise<string> {
    const report = this.generateMarkdown();
    const reportPath = path.join(
      process.cwd(),
      ".trailhound",
      "runs",
      this.manifest.run.id,
      "report.md"
    );
    await fs.writeFile(reportPath, report);
    return reportPath;
  }

  async generateHtml(): Promise<string> {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Trailhound Report - ${this.manifest.run.id}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      line-height: 1.6;
      padding: 2rem;
    }
    .container { max-width: 1000px; margin: 0 auto; }
    h1 { color: #58a6ff; margin-bottom: 1rem; }
    h2 { color: #79c0ff; margin-top: 2rem; margin-bottom: 1rem; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem; }
    .meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1rem 0; }
    .meta-item { background: #161b22; padding: 1rem; border-radius: 8px; border: 1px solid #30363d; }
    .meta-label { color: #8b949e; font-size: 0.85rem; text-transform: uppercase; }
    .meta-value { color: #c9d1d9; font-size: 1.1rem; font-weight: 500; }
    .risk { margin: 1rem 0; padding: 1rem; border-radius: 8px; }
    .risk-low { background: #238636; color: white; }
    .risk-medium { background: #d29922; color: #0d1117; }
    .risk-high { background: #da3633; color: white; }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin: 1rem 0; }
    .summary-item { background: #161b22; padding: 1.5rem; text-align: center; border-radius: 8px; border: 1px solid #30363d; }
    .summary-value { font-size: 2rem; font-weight: bold; color: #58a6ff; }
    .summary-label { color: #8b949e; font-size: 0.9rem; }
    .warning { background: #341a00; border-left: 4px solid #d29922; padding: 1rem; margin: 0.5rem 0; border-radius: 0 4px 4px 0; }
    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #30363d; color: #8b949e; font-size: 0.85rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🐕 Trailhound Report</h1>
    
    <div class="meta">
      <div class="meta-item">
        <div class="meta-label">Run ID</div>
        <div class="meta-value">${this.manifest.run.id}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Agent</div>
        <div class="meta-value">${this.manifest.agent.name}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Duration</div>
        <div class="meta-value">${this.formatDuration(this.manifest.run.durationMs)}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Exit Code</div>
        <div class="meta-value">${this.manifest.run.exitCode}</div>
      </div>
    </div>

    ${this.generateRiskHtml()}

    <h2>Summary</h2>
    <div class="summary">
      <div class="summary-item">
        <div class="summary-value">${this.manifest.summary.filesModified}</div>
        <div class="summary-label">Files Modified</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${this.manifest.summary.commandsRun}</div>
        <div class="summary-label">Commands Run</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${this.manifest.summary.networkConnections}</div>
        <div class="summary-label">Network Connections</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${this.manifest.summary.secretsAccessed}</div>
        <div class="summary-label">Secrets Accessed</div>
      </div>
    </div>

    ${this.generateWarningsHtml()}

    <div class="footer">
      Generated by Trailhound v0.1.0
    </div>
  </div>
</body>
</html>
`;

    const htmlPath = path.join(this.getRunDir(), "report.html");
    await fs.writeFile(htmlPath, html);
    return htmlPath;
  }

  private calculateRiskLevel(): { level: string; points: number; reasons: string[] } {
    let points = 0;
    const reasons: string[] = [];

    const summary = this.manifest.summary;

    // Files modified
    points += summary.filesModified * 1;
    
    // Commands run
    points += summary.commandsRun * 1;

    // Network connections
    if (summary.networkConnections > 0) {
      points += 4;
      reasons.push("external network activity");
    }

    // Secrets accessed - major risk
    if (summary.secretsAccessed > 0) {
      points += summary.secretsAccessed * 10;
      reasons.push("secret file access");
    }

    // Warnings
    points += this.manifest.warnings.length * 2;

    // Determine level
    let level = "Low 🟢";
    if (points >= 10) {
      level = "Medium 🟡";
    }
    if (points >= 20) {
      level = "High 🔴";
    }

    return { level, points, reasons };
  }

  private generateRiskHtml(): string {
    const risk = this.calculateRiskLevel();
    const riskClass = risk.points >= 20 ? "risk-high" : 
                      risk.points >= 10 ? "risk-medium" : "risk-low";
    
    return `
      <div class="risk ${riskClass}">
        <strong>Risk Score: ${risk.level}</strong>
        ${risk.points > 0 ? `<br>${risk.points} points - ${risk.reasons.join(", ")}` : ""}
      </div>
    `;
  }

  private generateWarningsHtml(): string {
    if (this.manifest.warnings.length === 0) return "";
    
    const warnings = this.manifest.warnings
      .map(w => `<div class="warning">⚠️  ${this.escapeHtml(w)}</div>`)
      .join("");
    
    return `
      <h2>Warnings</h2>
      ${warnings}
    `;
  }

  private formatDuration(ms: number): string {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    
    if (hours > 0) {
      return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
    }
    if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    }
    return `${seconds}s`;
  }

  private escapeHtml(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    };
    return text.replace(/[&<>"']/g, m => map[m]);
  }

  private getRunDir(): string {
    return path.join(process.cwd(), ".trailhound", "runs", this.manifest.run.id);
  }
}
